### ISSUE TITLE
Update to 2.6.38 fails

### ISSUE THREAD

**Issue by rlakey** [mitre/heimdall2#4066] opened 2023-02-09 17:56 UTC
**Describe the bug**
I did a restart of my pods in my Heimdall deployment to update to the latest version 2.6.38 and the pods would not start and are outputting this error.

```
yarn run v1.22.19
$ yarn workspace heimdall-server sequelize-cli db:migrate
$ ts-node --esm node_modules/.bin/sequelize db:migrate

Sequelize CLI [Node: 16.19.0, CLI: 6.6.0, ORM: 6.28.0]


ERROR: Error reading "db/database.ts". Error: TSError: ⨯ Unable to compile TypeScript:
config/app_config.ts(14,11): error TS2571: Object is of type 'unknown'.


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /usr/local/bin/node
Arguments: /opt/yarn-v1.22.19/lib/cli.js sequelize-cli db:migrate
Directory: /app/apps/backend
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Additional context**
Rolled back to 2.6.37 which seems to have worked although I do see 1 restart listed for those pods. Tried again to 2.6.38 with the same result.

**Comment by Amndeep7** [comment] 2023-02-09 21:48
Duplicate of https://github.com/mitre/heimdall2/issues/4064

**Closed by Amndeep7** 2023-02-09 21:48 UTC
Labels: bug
