### ISSUE TITLE
Integrate HDF converters with the frontend

### ISSUE THREAD

**Issue by rbclark** [mitre/heimdall2#1684] opened 2021-07-20 13:10 UTC
**Is your feature request related to a problem? Please describe.**
It would be nice to have the ability to drop burpsuite, fortify, etc, results onto Heimdall directly. With the HDF converters integrated into this repository, this is now a possibility: https://github.com/mitre/heimdall2/pull/1656

**Describe the solution you'd like**
Check if a file is of a type InspecJS understands, and if it is not then try all of the converters to see if any of them create a valid HDF result.

**Comment by camdenmoors** [comment] 2021-08-09 20:59
Duplicate of 1731, closing in preference of the newer issue.

**Closed by camdenmoors** 2021-08-09 20:59 UTC
Labels: enhancement, HDF Converters
