### ISSUE TITLE
[BUG] Github oauth name field is null instead of string

### ISSUE THREAD

**Issue by Amndeep7** [mitre/heimdall2#1777] opened 2021-08-10 21:00 UTC
**Describe the bug**
Heimdall-demo fails to log in using the github oauth process due to attempting to do a 'split' on a null.  A null occurs if the Github profile does not have a value set in the name field.  

**To Reproduce**
1. Make sure your github account does not have a name set in the profile.
2. Attempt to log in via oauth on heimdall-demo.mitre.org.
3. See the error where it says the reason is "Cannot read property 'split' of null".

**Expected behavior**
You should still be able to log in.

**Screenshots**
![image](https://user-images.githubusercontent.com/2015821/128934255-29972404-588c-4991-a400-1736a6f34b06.png)

**Additional context**
It's doing the split when trying to do a separate first name / last name sorta display in the user profile.  IMO that's not the move since some folks can have just the one name or multiple last names or not want to share their name in Github.  We should just pass through whatever we get from Github directly.  W/r to the little logo thing in the corner, it doesn't need to be the user's initials - it can be some sorta static or even dynamic symbol/graphic.

**Comment by rbclark** [comment] 2021-08-11 13:23
The issue is when people do provide a name it is useful to have that name on Heimdall. The reason for the split has nothing to do with the logo in the top right corner. It is more so that the sharing features of the app show more useful information to the user (instead of just showing an email it can show a name and email on the groups page for example). The current split works well enough with multiple names, it just operates under the assumption that the first word is their first name and everything else goes in last name. The easiest fix for this is to just check if name is `null | undefined` before passing it to the split function.

**Comment by Amndeep7** [comment] 2021-08-12 20:35
It does not do that split as you say it does with the first name only being the first word:
<img width="819" alt="image" src="https://user-images.githubusercontent.com/2015821/129266006-3323bc6d-cb40-45f9-967c-52ce65f19fb6.png">

**Closed** 2021-08-24 21:02 UTC
Labels: bug
